version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.7.3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: celery
      RABBITMQ_DEFAULT_PASS: password123
      RABBITMQ_DEFAULT_VHOST: my_vhost
    expose:
      - 5672
    restart: on-failure


  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=model1db
      - POSTGRES_USER=model1
      - POSTGRES_PASSWORD=model1pw
    restart: on-failure
    volumes:
       - postgresql-data:/var/lib/postgresql/data/

  web:
    build: ./proj
    command: ./run_web_prod.sh
    container_name: web
    image: web-image
    env_file:
      - .env
    expose:
      - 8000
    restart: on-failure
    volumes:
      # - ${LANSERVER_WORKFOLDER:?err}:/home/proj/web/Data/
      # - proj/PlotFiles:/home/proj/web/Data/
      - static_volume:/home/proj/web/static
      - media_volume:/home/proj/web/media
    depends_on:
      - postgres
      - rabbitmq

  celery_worker:
    build: ./proj
    image: web-image
    container_name: celery_worker
    command: ./run_celery_worker.sh
    restart: on-failure
    depends_on:
      - web
      - postgres
      - rabbitmq


  celery_beat:
    build: ./proj
    container_name: celery_beat
    image: web-image
    command: ./run_celery_beat.sh
    depends_on:
      - web
      - postgres
      - rabbitmq
    restart: on-failure


  nginx:
    build: ./nginx
    env_file:
      - .env
    ports:
      - ${WEBSERVER_PORT:?err}:80
    volumes:
      - static_volume:/home/proj/web/static
      - media_volume:/home/proj/web/media
    depends_on:
      - web
    restart: on-failure


volumes:
  postgresql-data:
  static_volume:
  media_volume:
